### ISSUE TITLE
【内推】抖音电商高级/资深后端工程师【30k-50k】

### ISSUE THREAD

**Issue by greyireland** [greyireland/algorithm-pattern#1]
高级 /资深后端开发工程师 [30k-50k]

1 、负责电商业务相关后台研发，优化订单、商品、物流等系统方案设计和实施；
2 、负责高质量的设计和编码，承担重点、难点的技术攻坚；
3 、参与产品讨论和开发实现。
4 、对系统稳定性、可扩展性、限流降级、高可用、异步化、可测性、可回溯等方面技术架构推推进落地；
5 、对现有架构、性能进行优化。

投递邮箱：fruitbag@163.com

目前我们团队是负责直播电商这块，也是公司主推项目，明星或大佬（罗永浩）都在抖音卖货，大量招人~

最近面试难度也有相应降低，有想法的可以试试啊~，急速内推，看到消息必回！

小福利：

【三餐房补车补】【MacPro 32G】【所有软件正版激活码】【月底发当月工资】

**Comment by qichaotang** [comment]
帮顶！！！
