### ISSUE TITLE
动态规划jump game ii超时

### ISSUE THREAD

**Issue by da183** [greyireland/algorithm-pattern#16]
[原文链接](https://greyireland.gitbook.io/algorithm-pattern/ji-chu-suan-fa-pian/dp#jump-game-ii)
我用C++重写后提交报超时，是贴的代码有问题么，还是单纯用动态规划做不了呢

**Comment by da183** [comment]
顺便，弱弱问一下，打卡，要怎么打呢，fork后在自己的仓库里替换上自己写的么

**Comment by greyireland** [comment]
> [原文链接](https://greyireland.gitbook.io/algorithm-pattern/ji-chu-suan-fa-pian/dp#jump-game-ii)
> 我用C++重写后提交报超时，是贴的代码有问题么，还是单纯用动态规划做不了呢

这个版本go可以过，我更新了v2解法，你可以参考一下

**Comment by greyireland** [comment]
> 顺便，弱弱问一下，打卡，要怎么打呢，fork后在自己的仓库里替换上自己写的么

所有题目完成之后，可以自己总结一下，写一篇文章，或者建一个仓库之类的都可以，然后我给你贴一个链接（或者你提一个pull requests）

**Comment by da183** [comment]
十分感谢，新的解法我学习一下。
从LeetCode的提交记录中龟速迁移中，等回头都完成了来找你打卡～
