### ISSUE TITLE
授权申请

### ISSUE THREAD

**Issue by ZhuPeng** [greyireland/algorithm-pattern#33]
我个人开发了一个[微信小程序](https://github.com/ZhuPeng/mp-githubtrending)，起初是做为尝试方便自己查看 GitHub 的开源项目和书籍，但是后续使用人数逐渐增多了。
    考虑到小程序上展示的项目都有对应的开源许可，可能会涉及对部分项目的侵权。
    我们观察到您的项目并没有在 GitHub 上设置任何的开源许可，所以想向您申请相关的许可，许可包括允许在小程序上展示和查看。
    以下是小程序的二维码，可以扫码查看。
    ![qrcode](https://7465-test-3c9b5e-1258459492.tcb.qcloud.la/qrcode.jpg)
    如果您觉得我已经侵犯了您的权利，请告知我，我将第一时间移除。
    

> From WeChat Mini Programe: [GitHub Trending Hub](https://github.com/ZhuPeng/mp-githubtrending?openid=undefined)

**Comment by Skylyyun** [comment]
如果有我的github有关项目，请移除，我并不希望自己的项目在你的小程序上显示，这侵犯了我的权利。



---原始邮件---
发件人: "ZhuPeng"<notifications@github.com&gt;
发送时间: 2020年10月7日(周三) 下午4:35
收件人: "greyireland/algorithm-pattern"<algorithm-pattern@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [greyireland/algorithm-pattern] 授权申请 (#33)




 
我个人开发了一个微信小程序，起初是做为尝试方便自己查看 GitHub 的开源项目和书籍，但是后续使用人数逐渐增多了。
 考虑到小程序上展示的项目都有对应的开源许可，可能会涉及对部分项目的侵权。
 我们观察到您的项目并没有在 GitHub 上设置任何的开源许可，所以想向您申请相关的许可，许可包括允许在小程序上展示和查看。
 以下是小程序的二维码，可以扫码查看。
 
 如果您觉得我已经侵犯了您的权利，请告知我，我将第一时间移除。
  
From WeChat Mini Programe: GitHub Trending Hub

**Comment by greyireland** [comment]
> 我个人开发了一个[微信小程序](https://github.com/ZhuPeng/mp-githubtrending)，起初是做为尝试方便自己查看 GitHub 的开源项目和书籍，但是后续使用人数逐渐增多了。
> 考虑到小程序上展示的项目都有对应的开源许可，可能会涉及对部分项目的侵权。
> 我们观察到您的项目并没有在 GitHub 上设置任何的开源许可，所以想向您申请相关的许可，许可包括允许在小程序上展示和查看。
> 以下是小程序的二维码，可以扫码查看。
> ![qrcode](https://camo.githubusercontent.com/5b67d143319059c6db221cbb473305b736d3fe66/68747470733a2f2f373436352d746573742d3363396235652d313235383435393439322e7463622e71636c6f75642e6c612f7172636f64652e6a7067)
> 如果您觉得我已经侵犯了您的权利，请告知我，我将第一时间移除。
> 
> > From WeChat Mini Programe: [GitHub Trending Hub](https://github.com/ZhuPeng/mp-githubtrending?openid=undefined)

请移除

**Comment by ZhuPeng** [comment]
@greyireland 好的，已经移除。谢谢。

**Comment by ZhuPeng** [comment]
另外还是建议给项目增加一个 License，这是 GitHub 的官方建议：https://choosealicense.com/no-permission/
